/* =======================================================
   BASE DE DATOS DE FRAGANCIAS — 211 productos
   Sincronizado con el catálogo oficial.
   Los bodysplashes llevan "subcategoria": "bodysplash".
   Las imágenes van sueltas en la raíz del proyecto.
   En "imagen" va la foto de la tarjeta.
   En "imagenFicha" va la foto que se ve en el detalle.
   ======================================================= */

   const PERFUMES = [

    /* ==================== MASCULINOS ==================== */
    {
      "codigo": "N2",
      "nombre": "212 Masculino",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Fougère / Amaderada",
      "perfil": "Fresco, limpio, urbano",
      "uso": "Día",
      "nota": "Un clásico urbano para uso cotidiano.",
      "imagen": "212MenCat.jpg",
      "imagenFicha": "212MenVertical.jpg"
    },
    {
      "codigo": "N4",
      "nombre": "212 Sexy Masculino",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Oriental / Especiada",
      "perfil": "Cálido, especiado, sensual",
      "uso": "Noche",
      "nota": "Perfil masculino sensual y envolvente.",
      "imagen": "212SexyMasculinoCat.jpeg",
      "imagenFicha": "212SexyMasculino.jpeg"
    },
    {
      "codigo": "N5",
      "nombre": "212 VIP Black",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Aromática / Gourmand",
      "perfil": "Dulce, lavanda, nocturno",
      "uso": "Noche",
      "nota": "Perfil joven, festivo y masculino.",
      "imagen": "212BlacCat.jpg",
      "imagenFicha": "212blackVertical.jpg"
    },
    {
      "codigo": "N7",
      "nombre": "212 VIP Masculino",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Ambarada / Aromática",
      "perfil": "Dulce, especiado, nocturno",
      "uso": "Noche",
      "nota": "Perfil joven y de fiesta.",
      "imagen": "212VipMenCat.jpeg",
      "imagenFicha": "212VipMenVertical.jpeg"
    },
    {
      "codigo": "N10",
      "nombre": "A-Men",
      "referencia": "Mugler",
      "categoria": "masculino",
      "familia": "Amaderada / Gourmand",
      "perfil": "Café, dulce, intenso",
      "uso": "Noche / invierno",
      "nota": "El clásico A-Men, potente y reconocible.",
      "imagen": "AMenCat.jpeg",
      "imagenFicha": "AMen.jpeg"
    },
    {
      "codigo": "N11",
      "nombre": "A-Men Pure Coffee",
      "referencia": "Mugler",
      "categoria": "masculino",
      "familia": "Gourmand / Amaderada",
      "perfil": "Café, dulce, intenso",
      "uso": "Noche / invierno",
      "nota": "Para amantes del café y perfumes potentes.",
      "imagen": "A-MenPureCoffeCat.jpeg",
      "imagenFicha": "A-menPureCoffeVertical.jpeg"
    },
    {
      "codigo": "N12",
      "nombre": "A-Men Pure Havane",
      "referencia": "Mugler",
      "categoria": "masculino",
      "familia": "Amaderada / Gourmand",
      "perfil": "Tabaco, miel, dulce",
      "uso": "Noche / invierno",
      "nota": "Perfil masculino dulce y tabacal.",
      "imagen": "AMenPureHavaneCat.jpeg",
      "imagenFicha": "AMenPureHavane.jpeg"
    },
    {
      "codigo": "N13",
      "nombre": "A-Men Pure Malt",
      "referencia": "Mugler",
      "categoria": "masculino",
      "familia": "Amaderada / Gourmand",
      "perfil": "Malta, dulce, madera",
      "uso": "Noche / invierno",
      "nota": "Para amantes de perfumes intensos y gourmand.",
      "imagen": "A-MenPureMaltCat.jpeg",
      "imagenFicha": "A-menPureMaltVertical.jpeg"
    },
    {
      "codigo": "N15",
      "nombre": "Acqua di Giò Masculino",
      "referencia": "Giorgio Armani",
      "categoria": "masculino",
      "familia": "Acuática / Cítrica",
      "perfil": "Fresco, marino, limpio",
      "uso": "Primavera / verano",
      "nota": "Clásico fresco y versátil para uso diario.",
      "imagen": "AcquaDiGioCat.jpeg",
      "imagenFicha": "AcquaDiGio.jpeg"
    },
    {
      "codigo": "N16",
      "nombre": "Acqua di Giò Profumo",
      "referencia": "Giorgio Armani",
      "categoria": "masculino",
      "familia": "Acuática / Amaderada",
      "perfil": "Marino, aromático, profundo",
      "uso": "Día y noche",
      "nota": "Fresco pero más serio y profundo que un acuático clásico.",
      "imagen": "AcquaDiGioProfumoCat.jpeg",
      "imagenFicha": "AcquaDiGioProfumo.jpeg"
    },
    {
      "codigo": "N20",
      "nombre": "Allure Homme Sport",
      "referencia": "Chanel",
      "categoria": "masculino",
      "familia": "Cítrica / Amaderada",
      "perfil": "Fresco, limpio, deportivo",
      "uso": "Día / verano",
      "nota": "Ideal para frescura elegante y deportiva.",
      "imagen": "AllureSportCat.jpeg",
      "imagenFicha": "AllureSport.jpeg"
    },
    {
      "codigo": "N21",
      "nombre": "Allure Masculino",
      "referencia": "Chanel",
      "categoria": "masculino",
      "familia": "Ambarada / Amaderada",
      "perfil": "Fresco, especiado, elegante",
      "uso": "Día y noche",
      "nota": "Versátil, elegante y sofisticado.",
      "imagen": "AllureHommeCat.jpeg",
      "imagenFicha": "AllureHomme.jpeg"
    },
    {
      "codigo": "N29",
      "nombre": "Armani Code Masculino",
      "referencia": "Giorgio Armani",
      "categoria": "masculino",
      "familia": "Ambarada / Especiada",
      "perfil": "Cálido, elegante, sensual",
      "uso": "Noche",
      "nota": "Clásico masculino para citas y ocasiones especiales.",
      "imagen": "ArmaniCodeCat.jpeg",
      "imagenFicha": "ArmaniCode.jpeg"
    },
    {
      "codigo": "N30",
      "nombre": "Armani Code Profumo",
      "referencia": "Giorgio Armani",
      "categoria": "masculino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, intenso",
      "uso": "Noche / invierno",
      "nota": "Para quien busca potencia y sensualidad.",
      "imagen": "ArmaniCodeProfumoCat.jpeg",
      "imagenFicha": "ArmaniCodeProfumo.jpeg"
    },
    {
      "codigo": "N32",
      "nombre": "Azzaro Pour Homme",
      "referencia": "Azzaro",
      "categoria": "masculino",
      "familia": "Aromática / Fougère",
      "perfil": "Fresco, herbal, clásico",
      "uso": "Día / todo el año",
      "nota": "Clásico masculino aromático fougère, con carácter y elegancia atemporal.",
      "imagen": "AzzaroPourHommeCat.jpeg",
      "imagenFicha": "AzzaroPourHomme.jpeg"
    },
    {
      "codigo": "N33",
      "nombre": "Bad Boy",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Ambarada / Amaderada",
      "perfil": "Dulce, especiado, masculino",
      "uso": "Noche",
      "nota": "Para un perfil joven, seductor y con carácter.",
      "imagen": "BadBoyCHCat.jpeg",
      "imagenFicha": "BadBoyCH.jpeg"
    },
    {
      "codigo": "N38",
      "nombre": "Black XS Masculino",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Amaderada / Gourmand",
      "perfil": "Dulce, especiado, juvenil",
      "uso": "Noche",
      "nota": "Perfil joven y seductor.",
      "imagen": "BlackXsCat.jpeg",
      "imagenFicha": "BlackXS.jpeg"
    },
    {
      "codigo": "N40",
      "nombre": "Black XS Afrodisíaco Masculino",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Amaderada / Gourmand",
      "perfil": "Dulce, intenso, juvenil",
      "uso": "Noche",
      "nota": "Para quien busca un aroma dulce y llamativo.",
      "imagen": "BlackXsLaphrodisiaqueCat.jpeg",
      "imagenFicha": "BlackXsLaphrodisiaque.jpeg"
    },
    {
      "codigo": "N42",
      "nombre": "Black XS L'Excès Masculino",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Dulce, especiado, juvenil",
      "uso": "Noche",
      "nota": "Perfil masculino joven y llamativo.",
      "imagen": "BlackXsLexcesCat.jpeg",
      "imagenFicha": "BlackXsLexces.jpeg"
    },
    {
      "codigo": "N44",
      "nombre": "Bleu de Chanel",
      "referencia": "Chanel",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Fresco, limpio, elegante",
      "uso": "Día y noche",
      "nota": "Una recomendación segura para quien busca elegancia y versatilidad.",
      "imagen": "BleudeChanelCat.jpeg",
      "imagenFicha": "BleudeChanel.jpeg"
    },
    {
      "codigo": "N46",
      "nombre": "Boss Bottled",
      "referencia": "Hugo Boss",
      "categoria": "masculino",
      "familia": "Amaderada / Frutal",
      "perfil": "Manzana, madera, especias",
      "uso": "Día y noche",
      "nota": "Uno de los perfiles masculinos más versátiles del catálogo.",
      "imagen": "HugoBossCat.jpeg",
      "imagenFicha": "HugoBoss.jpeg"
    },
    {
      "codigo": "N47",
      "nombre": "Boss Bottled Intense",
      "referencia": "Hugo Boss",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Cálido, especiado, masculino",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien busca un Boss más intenso y cálido.",
      "imagen": "HugoBossIntenseCat.jpeg",
      "imagenFicha": "HugoBossIntense.jpeg"
    },
    {
      "codigo": "N48",
      "nombre": "Boss Bottled Night",
      "referencia": "Hugo Boss",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Amaderado, limpio, nocturno",
      "uso": "Noche",
      "nota": "Perfil masculino elegante y nocturno.",
      "imagen": "HugoBossNigthCat.jpeg",
      "imagenFicha": "HugoBossNigth.jpeg"
    },
    {
      "codigo": "N50",
      "nombre": "Bvlgari Aqua Pour Homme",
      "referencia": "Bvlgari",
      "categoria": "masculino",
      "familia": "Acuática / Amaderada",
      "perfil": "Marino, fresco, masculino",
      "uso": "Primavera / verano",
      "nota": "Excelente para quien busca frescura marina.",
      "imagen": "BvlgariAquaCat.jpeg",
      "imagenFicha": "BvlgariAqua.jpeg"
    },
    {
      "codigo": "N51",
      "nombre": "Bvlgari Man in Black",
      "referencia": "Bvlgari",
      "categoria": "masculino",
      "familia": "Ambarada / Amaderada",
      "perfil": "Cálido, especiado, cuero",
      "uso": "Noche / invierno",
      "nota": "Masculino intenso y elegante.",
      "imagen": "BvlgariManInBlackCat.jpeg",
      "imagenFicha": "BvlgariManInBlack.jpeg"
    },
    {
      "codigo": "N53",
      "nombre": "Herrera for Men",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Aromática / Amaderada",
      "perfil": "Verde, fresco, masculino",
      "uso": "Día",
      "nota": "Clásico masculino elegante.",
      "imagen": "HerreraForMenCat.jpeg",
      "imagenFicha": "HerreraForMen.jpeg"
    },
    {
      "codigo": "N55",
      "nombre": "CH Masculino",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Ambarada / Amaderada",
      "perfil": "Dulce, especiado, elegante",
      "uso": "Día y noche",
      "nota": "Versátil y elegante para un público amplio.",
      "imagen": "ChMenCat.jpeg",
      "imagenFicha": "ChMen.jpeg"
    },
    {
      "codigo": "N61",
      "nombre": "CK Eternity Masculino",
      "referencia": "Calvin Klein",
      "categoria": "masculino",
      "familia": "Aromática / Fougère",
      "perfil": "Verde, limpio, clásico",
      "uso": "Día",
      "nota": "Masculino clásico para uso cotidiano.",
      "imagen": "CkEternityCat.jpeg",
      "imagenFicha": "CkEternity.jpeg"
    },
    {
      "codigo": "N68",
      "nombre": "Aventus",
      "referencia": "Creed",
      "categoria": "masculino",
      "familia": "Frutal / Amaderada",
      "perfil": "Fresco, elegante, sofisticado",
      "uso": "Día y noche",
      "nota": "Perfil masculino premium, elegante y distintivo.",
      "imagen": "AventusCreedCat.jpeg",
      "imagenFicha": "AventusCreed.jpeg"
    },
    {
      "codigo": "N70",
      "nombre": "Dior Homme",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Amaderada / Floral",
      "perfil": "Iris, amaderado, elegante",
      "uso": "Día y noche",
      "nota": "Perfil masculino elegante y refinado.",
      "imagen": "DiorHommeParfumCat.jpeg",
      "imagenFicha": "DiorHommeParfum.jpeg"
    },
    {
      "codigo": "N71",
      "nombre": "Dior Homme Intense",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Amaderada / Floral",
      "perfil": "Iris, amaderado, elegante",
      "uso": "Noche / otoño-invierno",
      "nota": "Perfil masculino elegante, serio y sofisticado.",
      "imagen": "DiorHommeIntnseCat.jpeg",
      "imagenFicha": "DiorHommeIntnse.jpeg"
    },
    {
      "codigo": "N72",
      "nombre": "Dior Homme Sport",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Cítrica / Amaderada",
      "perfil": "Fresco, cítrico, especiado",
      "uso": "Día / todo el año",
      "nota": "Frescura vibrante y cítrica con un fondo amaderado y especiado. Elegante y versátil.",
      "imagen": "DiorHommeSportCat.jpeg",
      "imagenFicha": "DiorHommeSport.jpeg"
    },
    {
      "codigo": "N73",
      "nombre": "Eros Masculino",
      "referencia": "Versace",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Fresco, dulce, intenso",
      "uso": "Noche / todo el año",
      "nota": "Un clásico para quien quiere presencia y sensualidad.",
      "imagen": "ErosCat.jpeg",
      "imagenFicha": "Eros.jpeg"
    },
    {
      "codigo": "N75",
      "nombre": "Fan di Fendi Masculino",
      "referencia": "Fendi",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Amaderado, cítrico, masculino",
      "uso": "Día y noche",
      "nota": "Perfil masculino moderno y elegante.",
      "imagen": "FanDiFendiCat.jpeg",
      "imagenFicha": "FanDiFendi.jpeg"
    },
    {
      "codigo": "N77",
      "nombre": "Fahrenheit",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Amaderada / Cuero",
      "perfil": "Cuero, violeta, amaderado",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien busca un clásico masculino con mucha personalidad.",
      "imagen": "FahrenheitDiorCat.jpeg",
      "imagenFicha": "FahrenheitDior.jpeg"
    },
    {
      "codigo": "N78",
      "nombre": "Fahrenheit 32",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Cítrica / Amaderada",
      "perfil": "Fresco, cítrico, amaderado",
      "uso": "Primavera / verano",
      "nota": "Versión más fresca y luminosa de Fahrenheit.",
      "imagen": "Fahrenheit32DiorCat.jpeg",
      "imagenFicha": "Fahrenheit32Dior.jpeg"
    },
    {
      "codigo": "N80",
      "nombre": "Gentlemen Only",
      "referencia": "Givenchy",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Fresco, especiado, elegante",
      "uso": "Día y noche",
      "nota": "Perfil masculino moderno y elegante.",
      "imagen": "GentlemenOnlyCat.jpeg",
      "imagenFicha": "GentlemenOnly.jpeg"
    },
    {
      "codigo": "N83",
      "nombre": "Herrera Aqua",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Acuática / Cítrica",
      "perfil": "Fresco, acuático, cítrico",
      "uso": "Primavera / verano",
      "nota": "Masculino fresco para clima cálido.",
      "imagen": "HerreraAquaChCat.jpeg",
      "imagenFicha": "HerreraAquaCh.jpeg"
    },
    {
      "codigo": "N88",
      "nombre": "Invictus",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Amaderada / Acuática",
      "perfil": "Fresco, dulce, deportivo",
      "uso": "Día / verano",
      "nota": "Perfil joven, deportivo y fácil de usar.",
      "imagen": "InvictusCat.jpeg",
      "imagenFicha": "Invictus.jpeg"
    },
    {
      "codigo": "N93",
      "nombre": "Kenzo Homme",
      "referencia": "Kenzo",
      "categoria": "masculino",
      "familia": "Amaderada / Acuática",
      "perfil": "Fresco, marino, amaderado",
      "uso": "Día / primavera-verano",
      "nota": "Clásico masculino fresco y elegante.",
      "imagen": "KenzoHommeCat.jpeg",
      "imagenFicha": "KenzoHomme.jpeg"
    },
    {
      "codigo": "N94",
      "nombre": "Kenzo Power",
      "referencia": "Kenzo",
      "categoria": "masculino",
      "familia": "Amaderada / Floral",
      "perfil": "Amaderado, floral, elegante",
      "uso": "Día y noche",
      "nota": "Perfil masculino sofisticado y menos convencional.",
      "imagen": "PowerKenzoCat.jpeg",
      "imagenFicha": "PowerKenzo.jpeg"
    },
    {
      "codigo": "N97",
      "nombre": "L'Eau d'Issey Pour Homme",
      "referencia": "Issey Miyake",
      "categoria": "masculino",
      "familia": "Acuática / Amaderada",
      "perfil": "Fresco, cítrico, especiado",
      "uso": "Primavera / verano",
      "nota": "Frescura acuática con yuzu y un fondo amaderado de sándalo y vetiver.",
      "imagen": "LEauDisseyHommeCat.jpeg",
      "imagenFicha": "LEauDisseyHomme.jpeg"
    },
    {
      "codigo": "N99",
      "nombre": "La Nuit de l'Homme",
      "referencia": "Yves Saint Laurent",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Cardamomo, madera, cálido",
      "uso": "Noche",
      "nota": "Muy apropiado para citas y salidas.",
      "imagen": "LaNuitYSLCat.jpeg",
      "imagenFicha": "LaNuitYSL.jpeg"
    },
    {
      "codigo": "N102",
      "nombre": "Le Beau",
      "referencia": "Jean Paul Gaultier",
      "categoria": "masculino",
      "familia": "Aromática / Amaderada",
      "perfil": "Fresco, coco, amaderado",
      "uso": "Día / verano",
      "nota": "Frescura aromática con un corazón cremoso de coco y fondo de haba tonka.",
      "imagen": "LeBeauJPGCat.jpeg",
      "imagenFicha": "LeBeauJPG.jpeg"
    },
    {
      "codigo": "N103",
      "nombre": "Le Male",
      "referencia": "Jean Paul Gaultier",
      "categoria": "masculino",
      "familia": "Fougère / Ambarada",
      "perfil": "Lavanda, vainilla, dulce",
      "uso": "Noche / otoño-invierno",
      "nota": "Clásico masculino, dulce y reconocible.",
      "imagen": "LeMaleCat.jpeg",
      "imagenFicha": "LeMale.jpeg"
    },
    {
      "codigo": "N105",
      "nombre": "Legend Spirit",
      "referencia": "Montblanc",
      "categoria": "masculino",
      "familia": "Aromática / Acuática",
      "perfil": "Fresco, limpio, masculino",
      "uso": "Día / verano",
      "nota": "Muy versátil para uso diario y clima cálido.",
      "imagen": "LegendSpiritCat.jpeg",
      "imagenFicha": "LegendSpirit.jpeg"
    },
    {
      "codigo": "N108",
      "nombre": "Light Blue Masculino",
      "referencia": "Dolce & Gabbana",
      "categoria": "masculino",
      "familia": "Cítrica / Aromática",
      "perfil": "Cítrico, fresco, marino",
      "uso": "Primavera / verano",
      "nota": "Clásico de verano y uso diario.",
      "imagen": "LightBlueD&GCat.jpeg",
      "imagenFicha": "LightBlueD&G.jpeg"
    },
    {
      "codigo": "N119",
      "nombre": "Nuit d'Issey Masculino",
      "referencia": "Issey Miyake",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Oscuro, amaderado, especiado",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien busca un masculino serio y nocturno.",
      "imagen": "NuitDisseyCat.jpeg",
      "imagenFicha": "NuitDissey.jpeg"
    },
    {
      "codigo": "N122",
      "nombre": "Ombré Leather",
      "referencia": "Tom Ford",
      "categoria": "masculino",
      "familia": "Cuero / Amaderada",
      "perfil": "Cuero, cálido, sofisticado",
      "uso": "Noche / otoño-invierno",
      "nota": "Para clientes que buscan un aroma oscuro y elegante.",
      "imagen": "OmbreLeatherCat.jpeg",
      "imagenFicha": "OmbreLeather.jpeg"
    },
    {
      "codigo": "N125",
      "nombre": "1 Million",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Ambarada / Especiada",
      "perfil": "Dulce, especiado, cuero",
      "uso": "Noche",
      "nota": "El clásico 1 Million, con su perfil dulce, especiado y cuero.",
      "imagen": "1MillionCat.jpeg",
      "imagenFicha": "1Millionn.jpeg"
    },
    {
      "codigo": "N126",
      "nombre": "1 Million Intense",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Ambarada / Especiada",
      "perfil": "Dulce, especiado, potente",
      "uso": "Noche",
      "nota": "Para clientes que quieren presencia y sensualidad.",
      "imagen": "1MillionIntenseCat.jpeg",
      "imagenFicha": "1MillionIntense.jpeg"
    },
    {
      "codigo": "N129",
      "nombre": "Paco Rabanne Masculino",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Verde, especiado, clásico",
      "uso": "Día",
      "nota": "Perfil masculino clásico y reconocible.",
      "imagen": "PacoRabanneVerdeCat.jpeg",
      "imagenFicha": "PacoRabanneVerde.jpeg"
    },
    {
      "codigo": "N130",
      "nombre": "Phantom",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Ambarada / Aromática",
      "perfil": "Dulce, fresco, moderno",
      "uso": "Noche",
      "nota": "Perfil joven, tecnológico y llamativo.",
      "imagen": "PhantomRabanneCat.jpeg",
      "imagenFicha": "PhantomRabanne.jpeg"
    },
    {
      "codigo": "N131",
      "nombre": "Pi",
      "referencia": "Givenchy",
      "categoria": "masculino",
      "familia": "Amaderada / Oriental",
      "perfil": "Vainilla, almendra, cálido",
      "uso": "Noche / otoño-invierno",
      "nota": "Clásico masculino cálido y avainillado.",
      "imagen": "PiGivenchyCat.jpeg",
      "imagenFicha": "PiGivenchy.jpeg"
    },
    {
      "codigo": "N134",
      "nombre": "Play Masculino",
      "referencia": "Givenchy",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Fresco, amaderado, moderno",
      "uso": "Día y noche",
      "nota": "Masculino urbano y versátil.",
      "imagen": "PlayEdPCat.jpeg",
      "imagenFicha": "PlayEdP.jpeg"
    },
    {
      "codigo": "N138",
      "nombre": "Polo Black",
      "referencia": "Ralph Lauren",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Frutal, especiado, amaderado",
      "uso": "Noche / otoño-invierno",
      "nota": "Fusión audaz de mango helado, artemisa plateada y pachulí noir.",
      "imagen": "PoloBlackCat.jpeg",
      "imagenFicha": "PoloBlack.jpeg"
    },
    {
      "codigo": "N139",
      "nombre": "Polo Blue",
      "referencia": "Ralph Lauren",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Fresco, acuático, herbal",
      "uso": "Día / primavera-verano",
      "nota": "Clásico fresco y elegante de Ralph Lauren.",
      "imagen": "PoloBlueCat.jpeg",
      "imagenFicha": "PoloBlue.jpeg"
    },
    {
      "codigo": "N140",
      "nombre": "Polo Ralph Lauren (clásico verde)",
      "referencia": "Ralph Lauren",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Verde, herbal, clásico",
      "uso": "Día / otoño",
      "nota": "Perfil masculino clásico, verde y elegante.",
      "imagen": "PoloRalphLaurenCat.jpeg",
      "imagenFicha": "PoloRalphLauren.jpeg"
    },
    {
      "codigo": "N141",
      "nombre": "Polo Red",
      "referencia": "Ralph Lauren",
      "categoria": "masculino",
      "familia": "Ambarada / Frutal",
      "perfil": "Dulce, fresco, energético",
      "uso": "Día y noche",
      "nota": "Masculino joven, frutal y deportivo.",
      "imagen": "PoloRedCat.jpeg",
      "imagenFicha": "PoloRed.jpeg"
    },
    {
      "codigo": "N144",
      "nombre": "Pure XS Masculino",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Gourmand / Ambarada",
      "perfil": "Dulce, vainilla, especiado",
      "uso": "Noche",
      "nota": "Para quien busca un masculino dulce y sensual.",
      "imagen": "PureXsRabanneCat.jpeg",
      "imagenFicha": "PureXsRabanne.jpeg"
    },
    {
      "codigo": "N148",
      "nombre": "Sauvage",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Fougère / Amaderada",
      "perfil": "Fresco, especiado, masculino",
      "uso": "Día y noche",
      "nota": "Una opción fácil de recomendar si busca algo masculino, versátil y conocido.",
      "imagen": "sauvageDiorCat.jpeg",
      "imagenFicha": "sauvageDior.jpeg"
    },
    {
      "codigo": "N151",
      "nombre": "Spicebomb",
      "referencia": "Viktor & Rolf",
      "categoria": "masculino",
      "familia": "Especiada / Amaderada",
      "perfil": "Especiado, cálido, masculino",
      "uso": "Noche / invierno",
      "nota": "Ideal para quien disfruta perfumes especiados y potentes.",
      "imagen": "SpicebombCat.jpeg",
      "imagenFicha": "Spicebomb.jpeg"
    },
    {
      "codigo": "N152",
      "nombre": "Starwalker",
      "referencia": "Montblanc",
      "categoria": "masculino",
      "familia": "Amaderada / Cítrica",
      "perfil": "Fresco, amaderado, limpio",
      "uso": "Día",
      "nota": "Perfil masculino discreto y versátil.",
      "imagen": "StarwalkerMontblancCat.jpeg",
      "imagenFicha": "StarwalkerMontblanc.jpeg"
    },
    {
      "codigo": "N153",
      "nombre": "Stronger With You",
      "referencia": "Emporio Armani",
      "categoria": "masculino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, envolvente",
      "uso": "Noche / otoño-invierno",
      "nota": "Muy buena opción para citas y salidas nocturnas.",
      "imagen": "StrongerWhitYouArmaniCat.jpeg",
      "imagenFicha": "StrongerWhitYouArmani.jpeg"
    },
    {
      "codigo": "N154",
      "nombre": "Terre d'Hermès",
      "referencia": "Hermès",
      "categoria": "masculino",
      "familia": "Amaderada / Cítrica",
      "perfil": "Cítrico, terroso, elegante",
      "uso": "Día / otoño",
      "nota": "Para quien prefiere elegancia sobria y un perfil más seco.",
      "imagen": "TerreHermesCat.jpeg",
      "imagenFicha": "TerreHermes.jpeg"
    },
    {
      "codigo": "N156",
      "nombre": "The One Masculino",
      "referencia": "Dolce & Gabbana",
      "categoria": "masculino",
      "familia": "Ambarada / Especiada",
      "perfil": "Cálido, especiado, elegante",
      "uso": "Noche / otoño-invierno",
      "nota": "Excelente perfil para citas y ocasiones especiales.",
      "imagen": "TheOneD&GCat.jpeg",
      "imagenFicha": "TheOneD&G.jpeg"
    },
    {
      "codigo": "N158",
      "nombre": "Tom Ford Extreme",
      "referencia": "Tom Ford",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Amaderado, elegante, diferente",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien busca un amaderado elegante y diferente.",
      "imagen": "MenExtremeTomfordCat.jpeg",
      "imagenFicha": "MenExtremeTomford.jpeg"
    },
    {
      "codigo": "N161",
      "nombre": "Tommy Hilfiger Masculino",
      "referencia": "Tommy Hilfiger",
      "categoria": "masculino",
      "familia": "Cítrica / Aromática",
      "perfil": "Fresco, limpio, casual",
      "uso": "Día",
      "nota": "Muy apropiado para uso diario.",
      "imagen": "TommyHilifigeCat.jpeg",
      "imagenFicha": "TommyHilifiger.jpeg"
    },
    {
      "codigo": "N162",
      "nombre": "Toy Boy",
      "referencia": "Moschino",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Rosa, especiado, moderno",
      "uso": "Noche / otoño-invierno",
      "nota": "Fragancia amaderada especiada para hombre, con rosa y especias.",
      "imagen": "ToyBoyMoschinoCat.jpeg",
      "imagenFicha": "ToyBoyMoschino.jpeg"
    },
    {
      "codigo": "N165",
      "nombre": "Ultra Male",
      "referencia": "Jean Paul Gaultier",
      "categoria": "masculino",
      "familia": "Gourmand / Ambarada",
      "perfil": "Dulce, vainilla, potente",
      "uso": "Noche / invierno",
      "nota": "Para clientes que buscan dulzura y mucha presencia.",
      "imagen": "UltraMaleCat.jpeg",
      "imagenFicha": "UltraMale.jpeg"
    },
    {
      "codigo": "N167",
      "nombre": "Valentino Uomo",
      "referencia": "Valentino",
      "categoria": "masculino",
      "familia": "Amaderada / Gourmand",
      "perfil": "Café, cuero, dulce",
      "uso": "Noche",
      "nota": "Masculino elegante y sensual.",
      "imagen": "ValentinoUomoCat.jpeg",
      "imagenFicha": "ValentinoUomo.jpeg"
    },
    {
      "codigo": "N169",
      "nombre": "Wanted",
      "referencia": "Azzaro",
      "categoria": "masculino",
      "familia": "Amaderada / Cítrica",
      "perfil": "Cítrico, especiado, masculino",
      "uso": "Día y noche",
      "nota": "Masculino moderno, fresco y con carácter.",
      "imagen": "WantedAzzaroCat.jpeg",
      "imagenFicha": "WantedAzzaro.jpeg"
    },
    {
      "codigo": "N171",
      "nombre": "212 Heroes Masculino",
      "referencia": "Carolina Herrera",
      "categoria": "masculino",
      "familia": "Fougère / Frutal",
      "perfil": "Fresco, frutal, juvenil",
      "uso": "Día",
      "nota": "Perfil joven, casual y deportivo.",
      "imagen": "212HeroesCat.jpeg",
      "imagenFicha": "212HeroesVertical.jpeg"
    },
    {
      "codigo": "N175",
      "nombre": "Scandal Masculino",
      "referencia": "Jean Paul Gaultier",
      "categoria": "masculino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, seductor",
      "uso": "Noche",
      "nota": "Para quien prefiere perfumes masculinos intensos y dulces.",
      "imagen": "ScandalCat.jpeg",
      "imagenFicha": "Scandal.jpeg"
    },
    {
      "codigo": "N176",
      "nombre": "Club de Nuit Intense",
      "referencia": "Armaf",
      "categoria": "masculino",
      "familia": "Amaderada / Frutal",
      "perfil": "Fresco, ahumado, masculino",
      "uso": "Día y noche",
      "nota": "Perfil masculino elegante, con salida fresca y fondo amaderado.",
      "imagen": "ClubDeNuitIntenseCat.jpeg",
      "imagenFicha": "ClubDeNuitIntense.jpeg"
    },
    {
      "codigo": "N177",
      "nombre": "Invictus Victory",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, vainilla, cítrico",
      "uso": "Noche / invierno",
      "nota": "Para quien busca un Invictus más cálido y dulce.",
      "imagen": "InvictusVictoryCat.jpeg",
      "imagenFicha": "InvictusVictory.jpeg"
    },
    {
      "codigo": "N185",
      "nombre": "Eros Flame",
      "referencia": "Versace",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Cítrico, especiado, dulce",
      "uso": "Noche / otoño-invierno",
      "nota": "Eros con un perfil más cálido y especiado.",
      "imagen": "ErosFlameCat.jpeg",
      "imagenFicha": "ErosFlame.jpeg"
    },
    {
      "codigo": "N192",
      "nombre": "Y Eau de Parfum Intense",
      "referencia": "Yves Saint Laurent",
      "categoria": "masculino",
      "familia": "Amaderada / Aromática",
      "perfil": "Fresco, amaderado, intenso",
      "uso": "Día y noche",
      "nota": "Masculino moderno, versátil y con buena presencia.",
      "imagen": "YEauDEParfumIntenseCat.jpeg",
      "imagenFicha": "YEauDEParfumIntense.jpeg"
    },
    {
      "codigo": "N193",
      "nombre": "Invictus Victory Elixir",
      "referencia": "Paco Rabanne",
      "categoria": "masculino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, intenso",
      "uso": "Noche / invierno",
      "nota": "Para quien busca un Invictus más oscuro y potente.",
      "imagen": "InvictusVictoryElixirCat.jpeg",
      "imagenFicha": "InvictusVictoryElixir.jpeg"
    },
    {
      "codigo": "N198",
      "nombre": "Sauvage Elixir",
      "referencia": "Dior",
      "categoria": "masculino",
      "familia": "Amaderada / Especiada",
      "perfil": "Especiado, cálido, muy intenso",
      "uso": "Noche / invierno",
      "nota": "Para clientes que buscan un Sauvage más intenso y concentrado.",
      "imagen": "SauvageElixirDiorCat.jpeg",
      "imagenFicha": "SauvageElixirDior.jpeg"
    },
    {
      "codigo": "N209",
      "nombre": "Le Male Elixir Absolu",
      "referencia": "Jean Paul Gaultier",
      "categoria": "masculino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, intenso",
      "uso": "Noche / invierno",
      "nota": "Para quien busca un perfume masculino intenso y dulce.",
      "imagen": "LeMaleElixirAbsoluCat.jpeg",
      "imagenFicha": "LeMaleElixirAbsolu.jpeg"
    },
  
    /* ==================== FEMENINOS ==================== */
    /* --- BODYSPLASHES --- */
    {
      "codigo": "BS1",
      "nombre": "Love Spell",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Frutal / Floral",
      "perfil": "Frutal, floral, dulce",
      "uso": "Día",
      "nota": "Body splash juvenil y romántico.",
      "imagen": "LoveSpellCat.jpeg",
      "imagenFicha": "LoveSpell.jpeg"
    },
    {
      "codigo": "BS2",
      "nombre": "Coconut Passion",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Gourmand / Oriental",
      "perfil": "Coco, vainilla, dulce",
      "uso": "Día / verano",
      "nota": "Para quien busca un aroma dulce, tropical y juvenil.",
      "imagen": "CoconutPassionCat.jpeg",
      "imagenFicha": "CoconutPassion.jpeg"
    },
    {
      "codigo": "BS3",
      "nombre": "Pure Seduction",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Frutal / Floral",
      "perfil": "Frutal, dulce, juvenil",
      "uso": "Día / verano",
      "nota": "Body splash juvenil y fresco para uso cotidiano.",
      "imagen": "PureSeductionCat.jpeg",
      "imagenFicha": "PureSeduction.jpeg"
    },
    {
      "codigo": "BS4",
      "nombre": "Rush",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Frutal / Floral",
      "perfil": "Cítrico, floral, dulce",
      "uso": "Día",
      "nota": "Body splash vibrante con clementina, flores blancas y un fondo cálido de ámbar y vainilla.",
      "imagen": "RushCat.jpeg",
      "imagenFicha": "Rush.jpeg"
    },
    {
      "codigo": "BS5",
      "nombre": "Bare Vanilla",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Gourmand / Amaderada",
      "perfil": "Dulce, cremoso, cálido",
      "uso": "Día y noche",
      "nota": "Body splash gourmand con vainilla, cacao y un fondo cremoso de sándalo.",
      "imagen": "BareVanillaCat.jpeg",
      "imagenFicha": "BareVanilla.jpeg"
    },
    {
      "codigo": "BS6",
      "nombre": "Velvet Petals",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Floral / Gourmand",
      "perfil": "Floral, dulce, cremoso",
      "uso": "Día y noche",
      "nota": "Body splash femenino, suave y dulce.",
      "imagen": "VelvetPetalsCat.jpeg",
      "imagenFicha": "VelvetPetals.jpeg"
    },
    {
      "codigo": "BS7",
      "nombre": "Midnight Bloom",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Floral / Amaderada",
      "perfil": "Floral, misterioso, nocturno",
      "uso": "Noche",
      "nota": "Body splash floral nocturno con jazmín y maderas oscuras.",
      "imagen": "MidnightBloomCat.jpeg",
      "imagenFicha": "MidnightBloom.jpeg"
    },
    {
      "codigo": "BS8",
      "nombre": "Amber Romance",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Ambarada / Gourmand",
      "perfil": "Ámbar, vainilla, dulce",
      "uso": "Noche / otoño-invierno",
      "nota": "Body splash cálido y dulce.",
      "imagen": "AmberRomanceCat.jpeg",
      "imagenFicha": "AmberRomance.jpeg"
    },
    {
      "codigo": "BS9",
      "nombre": "Aqua Kiss",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Acuática / Floral",
      "perfil": "Fresco, acuático, suave",
      "uso": "Día / verano",
      "nota": "Body splash fresco y ligero.",
      "imagen": "AquaKissCat.jpeg",
      "imagenFicha": "AquaKiss.jpeg"
    },
    {
      "codigo": "BS10",
      "nombre": "Pear Glacé",
      "referencia": "Victoria's Secret",
      "categoria": "femenino",
      "subcategoria": "bodysplash",
      "familia": "Frutal / Floral",
      "perfil": "Pera, fresco, dulce",
      "uso": "Día / verano",
      "nota": "Body splash frutal, juvenil y fácil de vender.",
      "imagen": "PearGlaceCat.jpeg",
      "imagenFicha": "PearGlace.jpeg"
    },
  
    /* --- FRAGANCIAS FEMENINAS --- */
    {
      "codigo": "N1",
      "nombre": "212 Femenino",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral, fresco, elegante",
      "uso": "Día y noche",
      "nota": "Clásico femenino fresco y versátil.",
      "imagen": "212FemeninoCat.jpeg",
      "imagenFicha": "212Femenino.jpeg"
    },
    {
      "codigo": "N3",
      "nombre": "212 Sexy Femenino",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, sensual",
      "uso": "Noche",
      "nota": "Ideal para citas y salidas.",
      "imagen": "212SexyFemeninoCat.jpeg",
      "imagenFicha": "212SexyFemenino.jpeg"
    },
    {
      "codigo": "N6",
      "nombre": "212 VIP Femenino",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Gourmand",
      "perfil": "Dulce, frutal, juvenil",
      "uso": "Noche",
      "nota": "Perfil femenino joven y festivo.",
      "imagen": "212VIPFemeninoCat.jpeg",
      "imagenFicha": "212VIPFemenino.jpeg"
    },
    {
      "codigo": "N8",
      "nombre": "212 VIP Rose",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Rosa, frutal, chispeante",
      "uso": "Noche",
      "nota": "Perfil femenino moderno y festivo.",
      "imagen": "212VIPRoseCat.jpeg",
      "imagenFicha": "212VIPRose.jpeg"
    },
    {
      "codigo": "N9",
      "nombre": "5ta Avenue",
      "referencia": "Elizabeth Arden",
      "categoria": "femenino",
      "familia": "Floral / Aldehídica",
      "perfil": "Floral, elegante, clásico",
      "uso": "Día y noche",
      "nota": "Clásico femenino elegante y atemporal.",
      "imagen": "5taAvenidaCat.jpeg",
      "imagenFicha": "5taAvenida.jpeg"
    },
    {
      "codigo": "N14",
      "nombre": "Acqua di Giò Femenino",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Floral / Acuática",
      "perfil": "Fresco, limpio, acuático",
      "uso": "Primavera / verano",
      "nota": "Para quien busca frescura femenina.",
      "imagen": "AcquadiGiòFemeninoCat.jpeg",
      "imagenFicha": "AcquadiGiòFemenino.jpeg"
    },
    {
      "codigo": "N17",
      "nombre": "Acqua di Gioia",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Acuática / Cítrica",
      "perfil": "Fresco, cítrico, limpio",
      "uso": "Primavera / verano",
      "nota": "Para quien busca frescura femenina y natural.",
      "imagen": "AcquadiGioiaCat.jpeg",
      "imagenFicha": "AcquadiGioia.jpeg"
    },
    {
      "codigo": "N18",
      "nombre": "Addict",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Vainilla, floral, intensa",
      "uso": "Noche / invierno",
      "nota": "Para quien busca un perfume femenino cálido y sensual.",
      "imagen": "AddictCat.jpeg",
      "imagenFicha": "Addict.jpeg"
    },
    {
      "codigo": "N19",
      "nombre": "Alien",
      "referencia": "Mugler",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Jazmín, cálido, intenso",
      "uso": "Noche",
      "nota": "Perfil femenino potente y muy reconocible.",
      "imagen": "AlienCat.jpeg",
      "imagenFicha": "Alien.jpeg"
    },
    {
      "codigo": "N22",
      "nombre": "Amarige",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Floral, dulce, clásico",
      "uso": "Día y noche",
      "nota": "Clásico femenino floral y luminoso.",
      "imagen": "AmarigeCat.jpeg",
      "imagenFicha": "Amarige.jpeg"
    },
    {
      "codigo": "N23",
      "nombre": "Amor Amor",
      "referencia": "Cacharel",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, dulce, juvenil",
      "uso": "Día y noche",
      "nota": "Romántico, juvenil y fácil de reconocer.",
      "imagen": "AmorAmorCat.jpeg",
      "imagenFicha": "AmorAmor.jpeg"
    },
    {
      "codigo": "N24",
      "nombre": "Anaïs Anaïs",
      "referencia": "Cacharel",
      "categoria": "femenino",
      "familia": "Floral",
      "perfil": "Floral blanco, suave, romántico",
      "uso": "Día / primavera",
      "nota": "Clásico femenino delicado y romántico.",
      "imagen": "AnaïsAnaïsCat.jpeg",
      "imagenFicha": "AnaïsAnaïs.jpeg"
    },
    {
      "codigo": "N25",
      "nombre": "Angel Femenino",
      "referencia": "Mugler",
      "categoria": "femenino",
      "familia": "Gourmand / Ambarada",
      "perfil": "Chocolate, vainilla, dulce",
      "uso": "Noche / invierno",
      "nota": "Clásico gourmand para amantes de perfumes muy dulces.",
      "imagen": "AngelFemeninoCat.jpeg",
      "imagenFicha": "AngelFemenino.jpeg"
    },
    {
      "codigo": "N26",
      "nombre": "Ange ou Démon",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, oscuro, elegante",
      "uso": "Noche",
      "nota": "Para quien busca un perfume femenino sofisticado.",
      "imagen": "AngeouDémonCat.jpeg",
      "imagenFicha": "AngeouDémon.jpeg"
    },
    {
      "codigo": "N27",
      "nombre": "Ange ou Démon Le Secret",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Cítrica",
      "perfil": "Fresco, floral, delicado",
      "uso": "Día / primavera",
      "nota": "Para quien prefiere un floral fresco y elegante.",
      "imagen": "AngeouDémonLeSecretCat.jpeg",
      "imagenFicha": "AngeouDémonLeSecret..jpeg"
    },
    {
      "codigo": "N28",
      "nombre": "Armani Code Femenino",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, dulce, elegante",
      "uso": "Noche",
      "nota": "Femenino sensual y sofisticado.",
      "imagen": "ArmaniCodeFemeninoCat.jpeg",
      "imagenFicha": "ArmaniCodeFemenino.jpeg"
    },
    {
      "codigo": "N31",
      "nombre": "Aura",
      "referencia": "Mugler",
      "categoria": "femenino",
      "familia": "Amaderada / Floral",
      "perfil": "Verde, floral, dulce",
      "uso": "Noche / otoño",
      "nota": "Para quien busca un perfume original y con personalidad.",
      "imagen": "AuraCat.jpeg",
      "imagenFicha": "Aura.jpeg"
    },
    {
      "codigo": "N34",
      "nombre": "Be Delicious Femenino",
      "referencia": "DKNY",
      "categoria": "femenino",
      "familia": "Frutal / Floral",
      "perfil": "Manzana, fresco, juvenil",
      "uso": "Día / primavera-verano",
      "nota": "Muy fácil de recomendar a quien busca algo fresco y frutal.",
      "imagen": "BeDeliciousFemeninoCat.jpeg",
      "imagenFicha": "BeDeliciousFemenino.jpeg"
    },
    {
      "codigo": "N35",
      "nombre": "Because It's You",
      "referencia": "Emporio Armani",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Dulce, frutal, femenino",
      "uso": "Día y noche",
      "nota": "Romántico, juvenil y fácil de usar.",
      "imagen": "BecauseIt'sYouCat.jpeg",
      "imagenFicha": "BecauseIt'sYou.jpeg"
    },
    {
      "codigo": "N36",
      "nombre": "Black Opium",
      "referencia": "Yves Saint Laurent",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Café, dulce, sensual",
      "uso": "Noche",
      "nota": "Ideal para quien disfruta los perfumes dulces con café.",
      "imagen": "BlackOpiumCat.jpeg",
      "imagenFicha": "BlackOpium.jpeg"
    },
    {
      "codigo": "N37",
      "nombre": "Black Orchid",
      "referencia": "Tom Ford",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Oscuro, floral, terroso",
      "uso": "Noche",
      "nota": "Para quien busca un aroma sofisticado y diferente.",
      "imagen": "BlackOrchidCat.jpeg",
      "imagenFicha": "BlackOrchid.jpeg"
    },
    {
      "codigo": "N39",
      "nombre": "Black XS Afrodisíacos Femenino",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Oriental / Amaderada",
      "perfil": "Dulce, especiado, afrodisíaco",
      "uso": "Noche",
      "nota": "Perfil femenino rebelde y seductor, con rosa, cacao y vainilla negra.",
      "imagen": "BlackXsAfrodisiacoFemCat.jpeg",
      "imagenFicha": "BlackXsAfrodisiacoFem.jpeg"
    },
    {
      "codigo": "N41",
      "nombre": "Black XS Femenino",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, dulce",
      "uso": "Noche",
      "nota": "Perfil femenino juvenil y seductor.",
      "imagen": "BlackXsFemeninoCat.jpeg",
      "imagenFicha": "BlackXsFemenino.jpeg"
    },
    {
      "codigo": "N43",
      "nombre": "Black XS L'Excès Femenino",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Dulce, frutal, intenso",
      "uso": "Noche",
      "nota": "Para quien busca un femenino dulce y llamativo.",
      "imagen": "BlackXsLexcesFemeninoCat.jpeg",
      "imagenFicha": "BlackXsLexcesFemenino.jpeg"
    },
    {
      "codigo": "N45",
      "nombre": "Bonbon",
      "referencia": "Victorio & Lucchino",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, floral, juvenil",
      "uso": "Día y noche",
      "nota": "Perfil femenino dulce y juvenil.",
      "imagen": "BonbonCat.jpeg",
      "imagenFicha": "Bombon.jpeg"
    },
    {
      "codigo": "N49",
      "nombre": "Bright Crystal",
      "referencia": "Versace",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Fresco, floral, luminoso",
      "uso": "Día / primavera-verano",
      "nota": "Clásico femenino fresco y elegante.",
      "imagen": "BrightCrystalCat.jpeg",
      "imagenFicha": "BrightCrystal.jpeg"
    },
    {
      "codigo": "N52",
      "nombre": "Carolina Herrera Femenino",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral, elegante, clásico",
      "uso": "Día y noche",
      "nota": "Para quien busca elegancia femenina clásica.",
      "imagen": "CarolinaHerreraFemeninoCat.jpeg",
      "imagenFicha": "CarolinaHerreraFemenino.jpeg"
    },
    {
      "codigo": "N54",
      "nombre": "Carolina Herrera Femenino Rojo",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Elegante, sensual, clásico",
      "uso": "Día y noche",
      "nota": "Clásico femenino elegante y seductor, con frutas cítricas, flores y maderas.",
      "imagen": "CHFemeninoRojoCat.jpeg",
      "imagenFicha": "CHFemeninoRojo.jpeg"
    },
    {
      "codigo": "N56",
      "nombre": "CH Sublime",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Chipre",
      "perfil": "Floral, elegante, sofisticado",
      "uso": "Día y noche",
      "nota": "Para quien busca un floral femenino refinado.",
      "imagen": "CHSublimeCat.jpeg",
      "imagenFicha": "CHSublime.jpeg"
    },
    {
      "codigo": "N57",
      "nombre": "Chance",
      "referencia": "Chanel",
      "categoria": "femenino",
      "familia": "Chipre / Floral",
      "perfil": "Fresco, floral, elegante",
      "uso": "Día y noche",
      "nota": "Elegante y versátil, con perfil femenino sofisticado.",
      "imagen": "ChanceCat.jpeg",
      "imagenFicha": "Chance.jpeg"
    },
    {
      "codigo": "N58",
      "nombre": "Chanel N°5",
      "referencia": "Chanel",
      "categoria": "femenino",
      "familia": "Floral / Aldehídica",
      "perfil": "Floral, elegante, clásico",
      "uso": "Día y noche",
      "nota": "Ícono de perfumería para quien busca elegancia clásica.",
      "imagen": "ChanelN°5Cat.jpeg",
      "imagenFicha": "ChanelN°5.jpeg"
    },
    {
      "codigo": "N59",
      "nombre": "CK Escape Femenino",
      "referencia": "Calvin Klein",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Fresco, frutal, femenino",
      "uso": "Día / primavera-verano",
      "nota": "Para quien busca frescura femenina casual.",
      "imagen": "CKEscapeFemeninoCat.jpeg",
      "imagenFicha": "CKEscapeFemenino.jpeg"
    },
    {
      "codigo": "N60",
      "nombre": "CK Eternity Femenino",
      "referencia": "Calvin Klein",
      "categoria": "femenino",
      "familia": "Floral",
      "perfil": "Floral, limpio, clásico",
      "uso": "Día",
      "nota": "Perfil femenino limpio y tradicional.",
      "imagen": "CKEternityFemeninoCat.jpeg",
      "imagenFicha": "CKEternityFemenino.jpeg"
    },
    {
      "codigo": "N62",
      "nombre": "Euphoria CK",
      "referencia": "Calvin Klein",
      "categoria": "femenino",
      "familia": "Oriental / Floral",
      "perfil": "Dulce, oriental, sensual",
      "uso": "Noche / otoño-invierno",
      "nota": "Perfil femenino intenso y envolvente.",
      "imagen": "EuphoriaCKCat.jpeg",
      "imagenFicha": "EuphoriaCK.jpeg"
    },
    {
      "codigo": "N64",
      "nombre": "Classique",
      "referencia": "Jean Paul Gaultier",
      "categoria": "femenino",
      "familia": "Floral / Oriental",
      "perfil": "Floral, dulce, sensual",
      "uso": "Noche",
      "nota": "Clásico femenino floral oriental. La irresistible tentación de Jean Paul Gaultier.",
      "imagen": "ClassiqueJPGCat.jpeg",
      "imagenFicha": "ClassiqueJPG.jpeg"
    },
    {
      "codigo": "N65",
      "nombre": "Coco Chanel",
      "referencia": "Chanel",
      "categoria": "femenino",
      "familia": "Ambarada / Floral",
      "perfil": "Cálido, especiado, elegante",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien busca un clásico femenino sofisticado.",
      "imagen": "CocoChanelCat.jpeg",
      "imagenFicha": "CocoChanel.jpeg"
    },
    {
      "codigo": "N66",
      "nombre": "Coco Mademoiselle",
      "referencia": "Chanel",
      "categoria": "femenino",
      "familia": "Chipre / Floral",
      "perfil": "Cítrico, floral, elegante",
      "uso": "Día y noche",
      "nota": "Clásico femenino elegante y versátil.",
      "imagen": "CocoMademoiselleCat.jpeg",
      "imagenFicha": "CocoMademoiselle.jpeg"
    },
    {
      "codigo": "N67",
      "nombre": "Cool Water Femenino",
      "referencia": "Davidoff",
      "categoria": "femenino",
      "familia": "Acuática / Floral",
      "perfil": "Fresco, acuático, limpio",
      "uso": "Primavera / verano",
      "nota": "Clásico fresco para uso diario.",
      "imagen": "coolWaterFemeninoCat.jpeg",
      "imagenFicha": "CoolWaterFemenino.jpeg"
    },
    {
      "codigo": "N69",
      "nombre": "DKNY Femenino",
      "referencia": "DKNY",
      "categoria": "femenino",
      "familia": "Cítrica / Floral",
      "perfil": "Fresco, cítrico, urbano",
      "uso": "Día / primavera-verano",
      "nota": "Ligero y fácil de usar.",
      "imagen": "DKNYFemeninoCat.jpeg",
      "imagenFicha": "DKNYFemenino.jpeg"
    },
    {
      "codigo": "N74",
      "nombre": "Fan di Fendi Femenino",
      "referencia": "Fendi",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, dulce",
      "uso": "Día y noche",
      "nota": "Femenino moderno y sofisticado.",
      "imagen": "FandiFendiFemeninoCat.jpeg",
      "imagenFicha": "FandiFendiFemenino.jpeg"
    },
    {
      "codigo": "N76",
      "nombre": "Fantasy",
      "referencia": "Britney Spears",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, frutal, vainilla",
      "uso": "Día y noche",
      "nota": "Juvenil, dulce y muy fácil de reconocer.",
      "imagen": "FantasyCat.jpeg",
      "imagenFicha": "Fantasy.jpeg"
    },
    {
      "codigo": "N79",
      "nombre": "Flowerbomb",
      "referencia": "Viktor & Rolf",
      "categoria": "femenino",
      "familia": "Floral / Gourmand",
      "perfil": "Floral, dulce, intenso",
      "uso": "Noche",
      "nota": "Perfil femenino floral y dulce muy reconocible.",
      "imagen": "FlowerbombCat.jpeg",
      "imagenFicha": "Flowerbomb.jpeg"
    },
    {
      "codigo": "N81",
      "nombre": "Good Girl",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Gourmand",
      "perfil": "Dulce, sensual, elegante",
      "uso": "Noche",
      "nota": "Para quien quiere un aroma femenino, dulce y seductor.",
      "imagen": "GoodGirlCat.jpeg",
      "imagenFicha": "GoodGirl.jpeg"
    },
    {
      "codigo": "N82",
      "nombre": "Halloween",
      "referencia": "Jesús del Pozo",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Dulce, floral, misterioso",
      "uso": "Noche",
      "nota": "Perfil femenino dulce y diferente.",
      "imagen": "HalloweenCat.jpeg",
      "imagenFicha": "Halloween.jpeg"
    },
    {
      "codigo": "N84",
      "nombre": "Hot Couture",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Dulce, floral, cálido",
      "uso": "Noche",
      "nota": "Femenino elegante y sensual.",
      "imagen": "HotCoutureCat.jpeg",
      "imagenFicha": "HotCouture.jpeg"
    },
    {
      "codigo": "N85",
      "nombre": "Hypnotic Poison",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Gourmand / Oriental",
      "perfil": "Almendra, vainilla, cálido",
      "uso": "Noche / invierno",
      "nota": "Clásico femenino dulce y adictivo.",
      "imagen": "HypnoticPoisonCat.jpeg",
      "imagenFicha": "HypnoticPoison.jpeg"
    },
    {
      "codigo": "N86",
      "nombre": "Idôle",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Floral",
      "perfil": "Rosa, limpio, moderno",
      "uso": "Día / primavera",
      "nota": "Para quien busca un floral femenino moderno y luminoso.",
      "imagen": "IdôleCat.jpeg",
      "imagenFicha": "Idôle.jpeg"
    },
    {
      "codigo": "N87",
      "nombre": "Insolence",
      "referencia": "Guerlain",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Violeta, dulce, empolvado",
      "uso": "Día y noche",
      "nota": "Para quien busca un floral femenino diferente.",
      "imagen": "InsolenceCat.jpeg",
      "imagenFicha": "Insolence.jpeg"
    },
    {
      "codigo": "N89",
      "nombre": "J'adore",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Floral",
      "perfil": "Floral, elegante, femenino",
      "uso": "Día y noche",
      "nota": "Clásico floral para quien busca elegancia femenina.",
      "imagen": "J'adoreCat.jpeg",
      "imagenFicha": "J'adore.jpeg"
    },
    {
      "codigo": "N90",
      "nombre": "Jungle Femenino",
      "referencia": "Kenzo",
      "categoria": "femenino",
      "familia": "Ambarada / Especiada",
      "perfil": "Especiado, cálido, exótico",
      "uso": "Noche / invierno",
      "nota": "Para quien busca un perfume femenino intenso y diferente.",
      "imagen": "JungleFemeninoCat.jpeg",
      "imagenFicha": "JungleFemenino.jpeg"
    },
    {
      "codigo": "N91",
      "nombre": "Kenzo Amour",
      "referencia": "Kenzo",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, arroz, vainilla",
      "uso": "Noche",
      "nota": "Femenino dulce, cálido y envolvente.",
      "imagen": "KenzoamourCat.jpeg",
      "imagenFicha": "KenzoAmour.jpeg"
    },
    {
      "codigo": "N92",
      "nombre": "Kenzo Flower",
      "referencia": "Kenzo",
      "categoria": "femenino",
      "familia": "Floral / Oriental",
      "perfil": "Floral, empolvado, elegante",
      "uso": "Día y noche",
      "nota": "Clásico floral femenino, suave y elegante.",
      "imagen": "KenzoFlowerCat.jpeg",
      "imagenFicha": "KenzoFlower.jpeg"
    },
    {
      "codigo": "N95",
      "nombre": "Kenzo World",
      "referencia": "Kenzo",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, moderno",
      "uso": "Día",
      "nota": "Perfil femenino fresco y moderno.",
      "imagen": "KenzoWorldCat.jpeg",
      "imagenFicha": "KenzoWorld.jpeg"
    },
    {
      "codigo": "N96",
      "nombre": "L'Eau d'Issey Femenino",
      "referencia": "Issey Miyake",
      "categoria": "femenino",
      "familia": "Floral / Acuática",
      "perfil": "Fresco, acuático, floral",
      "uso": "Primavera / verano",
      "nota": "Para quien busca limpieza, frescura y elegancia.",
      "imagen": "L'Eaud'IsseyFemeninoCat.jpeg",
      "imagenFicha": "L'Eaud'IsseyFemenino.jpeg"
    },
    {
      "codigo": "N98",
      "nombre": "L'Eau par Kenzo",
      "referencia": "Kenzo",
      "categoria": "femenino",
      "familia": "Acuática / Floral",
      "perfil": "Fresco, acuático, limpio",
      "uso": "Primavera / verano",
      "nota": "Clásico femenino fresco y acuático.",
      "imagen": "LEauparKenzoCat.jpeg",
      "imagenFicha": "LEauparKenzo.jpeg"
    },
    {
      "codigo": "N100",
      "nombre": "La Vie Est Belle",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, elegante, femenino",
      "uso": "Día y noche",
      "nota": "Ideal para quien busca un perfume dulce, femenino y muy reconocible.",
      "imagen": "LaVieEstBelleCat.jpeg",
      "imagenFicha": "LaVieEstBelle.jpeg"
    },
    {
      "codigo": "N101",
      "nombre": "Lady Million",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Dulce, floral, elegante",
      "uso": "Noche",
      "nota": "Femenino, glamoroso y llamativo.",
      "imagen": "LadyMillionCat.jpeg",
      "imagenFicha": "LadyMillion.jpeg"
    },
    {
      "codigo": "N104",
      "nombre": "Le Parfum de Elia Saab Femenino",
      "referencia": "Elie Saab",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral blanco, cálido, elegante",
      "uso": "Noche",
      "nota": "Para quien busca un floral femenino sofisticado.",
      "imagen": "LeParfumdeEliaSaabFemeninoCat.jpeg",
      "imagenFicha": "LeParfumdeEliaSaabFemenino.jpeg"
    },
    {
      "codigo": "N106",
      "nombre": "Libre",
      "referencia": "Yves Saint Laurent",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, elegante, ligeramente dulce",
      "uso": "Día y noche",
      "nota": "Para una mujer moderna que busca un floral con carácter.",
      "imagen": "LibreCat.jpeg",
      "imagenFicha": "Libre.jpeg"
    },
    {
      "codigo": "N107",
      "nombre": "Light Blue Femenino",
      "referencia": "Dolce & Gabbana",
      "categoria": "femenino",
      "familia": "Cítrica / Floral",
      "perfil": "Fresco, cítrico, veraniego",
      "uso": "Primavera / verano",
      "nota": "Perfecto para quien quiere frescura y sensación de verano.",
      "imagen": "LightBlueFEmeninoCat.jpeg",
      "imagenFicha": "LightBlueFemenino.jpeg"
    },
    {
      "codigo": "N109",
      "nombre": "L'Interdit",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral blanco, oscuro, elegante",
      "uso": "Noche / todo el año",
      "nota": "Floral sofisticado con un lado más intenso.",
      "imagen": "L'InterditCat.jpeg",
      "imagenFicha": "L'Interdit.jpeg"
    },
    {
      "codigo": "N110",
      "nombre": "Midnight Poison",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Ambarada / Floral",
      "perfil": "Oscuro, dulce, misterioso",
      "uso": "Noche / invierno",
      "nota": "Para quien busca un aroma femenino intenso y nocturno.",
      "imagen": "MidnightPoisonCat.jpeg",
      "imagenFicha": "MidnightPoison.jpeg"
    },
    {
      "codigo": "N111",
      "nombre": "Miracle",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral, fresco, elegante",
      "uso": "Día",
      "nota": "Para una mujer que busca un floral luminoso.",
      "imagen": "MiracleCat.jpeg",
      "imagenFicha": "Miracle.jpeg"
    },
    {
      "codigo": "N112",
      "nombre": "Miss Dior",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Floral / Chipre",
      "perfil": "Floral, elegante, romántico",
      "uso": "Día y noche",
      "nota": "Muy vendible para quien busca feminidad y elegancia.",
      "imagen": "MissDiorCat.jpeg",
      "imagenFicha": "MissDior.jpeg"
    },
    {
      "codigo": "N113",
      "nombre": "Miss Dior Cherie",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, dulce, juvenil",
      "uso": "Día",
      "nota": "Perfil femenino juvenil y frutal.",
      "imagen": "MissDiorCherieCat.jpeg",
      "imagenFicha": "MissDiorCherie.jpeg"
    },
    {
      "codigo": "N114",
      "nombre": "Mon Paris",
      "referencia": "Yves Saint Laurent",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Dulce, frutal, sensual",
      "uso": "Noche",
      "nota": "Para amantes de perfumes románticos y dulces.",
      "imagen": "MonParisCat.jpeg",
      "imagenFicha": "MonParis.jpeg"
    },
    {
      "codigo": "N115",
      "nombre": "My Way",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Floral",
      "perfil": "Floral, luminoso, femenino",
      "uso": "Día / primavera",
      "nota": "Para una mujer que busca un floral elegante y moderno.",
      "imagen": "MyWayCat.jpeg",
      "imagenFicha": "MyWay.jpeg"
    },
    {
      "codigo": "N116",
      "nombre": "Narciso For Her",
      "referencia": "Narciso Rodriguez",
      "categoria": "femenino",
      "familia": "Floral / Almizclada",
      "perfil": "Almizcle, floral, elegante",
      "uso": "Día y noche",
      "nota": "Para quien busca un perfume limpio, sensual y sofisticado.",
      "imagen": "NarcisoForHerCat.jpeg",
      "imagenFicha": "NarcisoForHer.jpeg"
    },
    {
      "codigo": "N118",
      "nombre": "Nina",
      "referencia": "Nina Ricci",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, fresco, dulce",
      "uso": "Día / primavera",
      "nota": "Juvenil, femenino y fácil de recomendar.",
      "imagen": "NinaCat.jpeg",
      "imagenFicha": "Nina.jpeg"
    },
    {
      "codigo": "N120",
      "nombre": "Ô de Lancôme",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Cítrica / Aromática",
      "perfil": "Cítrico, verde, fresco",
      "uso": "Día / verano",
      "nota": "Para quien busca frescura clásica.",
      "imagen": "ÔdeLancômeCat.jpeg",
      "imagenFicha": "ÔdeLancôme.jpeg"
    },
    {
      "codigo": "N121",
      "nombre": "Olympéa",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Floral / Oriental",
      "perfil": "Dulce, salado, sensual",
      "uso": "Noche / todo el año",
      "nota": "Perfil femenino moderno y sensual.",
      "imagen": "OlympeaCat.jpeg",
      "imagenFicha": "Olympea.jpeg"
    },
    {
      "codigo": "N123",
      "nombre": "Omnia Coral",
      "referencia": "Bvlgari",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, fresco",
      "uso": "Primavera / verano",
      "nota": "Perfecto para quien busca un floral fresco y juvenil.",
      "imagen": "OmniaCoralCat.jpeg",
      "imagenFicha": "OmniaCoral.jpeg"
    },
    {
      "codigo": "N124",
      "nombre": "Omnia Crystalline",
      "referencia": "Bvlgari",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Fresco, limpio, suave",
      "uso": "Día / primavera-verano",
      "nota": "Para quien busca un perfume delicado y limpio.",
      "imagen": "omniaCrystallineCat.jpeg",
      "imagenFicha": "omniaCrystalline.jpeg"
    },
    {
      "codigo": "N127",
      "nombre": "Organza",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Ambarada / Floral",
      "perfil": "Floral, vainilla, cálido",
      "uso": "Noche",
      "nota": "Perfil femenino elegante, clásico y sensual.",
      "imagen": "OrganzaCat.jpeg",
      "imagenFicha": "Organza.jpeg"
    },
    {
      "codigo": "N132",
      "nombre": "Play Femenino",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral, moderno, elegante",
      "uso": "Día y noche",
      "nota": "Perfil femenino moderno y versátil.",
      "imagen": "PlayFemeninoCat.jpeg",
      "imagenFicha": "PlayFemenino.jpeg"
    },
    {
      "codigo": "N133",
      "nombre": "Play Intense Femenino",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Dulce, floral, intenso",
      "uso": "Noche",
      "nota": "Para quien busca un floral femenino con más presencia.",
      "imagen": "PlayFemeninoIntenseCat.jpeg",
      "imagenFicha": "PlayFemeninoIntense.jpeg"
    },
    {
      "codigo": "N135",
      "nombre": "Poême",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, dulce, intenso",
      "uso": "Noche / invierno",
      "nota": "Para amantes de perfumes florales clásicos y potentes.",
      "imagen": "PoêmeCat.jpeg",
      "imagenFicha": "Poême.jpeg"
    },
    {
      "codigo": "N136",
      "nombre": "Poison",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Ambarada / Floral",
      "perfil": "Dulce, especiado, intenso",
      "uso": "Noche / invierno",
      "nota": "Clásico intenso para amantes de perfumes con carácter.",
      "imagen": "PoisonCat.jpeg",
      "imagenFicha": "Poison.jpeg"
    },
    {
      "codigo": "N137",
      "nombre": "Poison Girl",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Vainilla, dulce, sensual",
      "uso": "Noche / invierno",
      "nota": "Para amantes de los perfumes dulces y femeninos.",
      "imagen": "PoisonGirlCat.jpeg",
      "imagenFicha": "PoisonGirl.jpeg"
    },
    {
      "codigo": "N142",
      "nombre": "Pure Poison",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Floral blanco, limpio, sensual",
      "uso": "Día y noche",
      "nota": "Para quien busca un floral elegante y luminoso.",
      "imagen": "PurePoisonCat.jpeg",
      "imagenFicha": "PurePoison.jpeg"
    },
    {
      "codigo": "N143",
      "nombre": "Pure XS Femenino",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, sensual, vainilla",
      "uso": "Noche",
      "nota": "Para amantes de perfumes dulces y seductores.",
      "imagen": "PureXSFemeninoCat.jpeg",
      "imagenFicha": "PureXSFemenino.jpeg"
    },
    {
      "codigo": "N145",
      "nombre": "Ralph",
      "referencia": "Ralph Lauren",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Fresco, frutal, femenino",
      "uso": "Día / primavera-verano",
      "nota": "Aroma femenino juvenil y fresco.",
      "imagen": "RalphCat.jpeg",
      "imagenFicha": "Ralph.jpeg"
    },
    {
      "codigo": "N146",
      "nombre": "Ralph Blue Femenino",
      "referencia": "Ralph Lauren",
      "categoria": "femenino",
      "familia": "Floral / Acuática",
      "perfil": "Fresco, limpio, veraniego",
      "uso": "Primavera / verano",
      "nota": "Perfil femenino fresco y juvenil.",
      "imagen": "RalphBlueFemeninoCat.jpeg",
      "imagenFicha": "RalphBlueFemenino.jpeg"
    },
    {
      "codigo": "N147",
      "nombre": "Ricci Ricci",
      "referencia": "Nina Ricci",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, dulce",
      "uso": "Día y noche",
      "nota": "Juvenil, femenino y romántico.",
      "imagen": "RicciRicciCat.jpeg",
      "imagenFicha": "RicciRicci.jpeg"
    },
    {
      "codigo": "N149",
      "nombre": "Scandal Femenino",
      "referencia": "Jean Paul Gaultier",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, miel, sensual",
      "uso": "Noche",
      "nota": "Muy buena opción para amantes de perfumes dulces.",
      "imagen": "ScandalFemeninoCat.jpeg",
      "imagenFicha": "ScandalFemenino.jpeg"
    },
    {
      "codigo": "N150",
      "nombre": "Sì Armani",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Chipre / Floral",
      "perfil": "Cassis, rosa, vainilla",
      "uso": "Día y noche",
      "nota": "Femenino elegante, moderno y refinado.",
      "imagen": "SiArmaniCat.jpeg",
      "imagenFicha": "SiArmani.jpeg"
    },
    {
      "codigo": "N160",
      "nombre": "Tommy Girl",
      "referencia": "Tommy Hilfiger",
      "categoria": "femenino",
      "familia": "Floral / Cítrica",
      "perfil": "Fresco, floral, juvenil",
      "uso": "Día / primavera-verano",
      "nota": "Para quien quiere un perfume femenino fresco y casual.",
      "imagen": "TommyHilfigerCat.jpeg",
      "imagenFicha": "TommyHilfiger.jpeg"
    },
    {
      "codigo": "N163",
      "nombre": "Trésor",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Floral, frutal, cálido",
      "uso": "Día y noche",
      "nota": "Clásico femenino romántico.",
      "imagen": "TrésorCat.jpeg",
      "imagenFicha": "Trésor.jpeg"
    },
    {
      "codigo": "N164",
      "nombre": "Trésor La Nuit",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, frutal, cálido",
      "uso": "Noche / invierno",
      "nota": "Para amantes de perfumes dulces y románticos.",
      "imagen": "TrésorLaNuitCat.jpeg",
      "imagenFicha": "TrésorLaNuit.jpeg"
    },
    {
      "codigo": "N166",
      "nombre": "Ultraviolet Femenino",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Ambarada / Floral",
      "perfil": "Dulce, floral, moderno",
      "uso": "Noche",
      "nota": "Perfume femenino intenso y diferente.",
      "imagen": "UltravioletFemeninoCat.jpeg",
      "imagenFicha": "UltravioletFemenino.jpeg"
    },
    {
      "codigo": "N168",
      "nombre": "Very Irresistible Femenino",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral",
      "perfil": "Rosa, fresco, femenino",
      "uso": "Día / primavera",
      "nota": "Floral romántico y femenino.",
      "imagen": "VeryIrresistibleFemeninoCat.jpeg",
      "imagenFicha": "VeryIrresistibleFemenino.jpeg"
    },
    {
      "codigo": "N170",
      "nombre": "Womanity",
      "referencia": "Mugler",
      "categoria": "femenino",
      "familia": "Amaderada / Frutal",
      "perfil": "Dulce, salado, original",
      "uso": "Día y noche",
      "nota": "Para quien busca un perfume femenino poco convencional.",
      "imagen": "WomanityCat.jpeg",
      "imagenFicha": "Womanity.jpeg"
    },
    {
      "codigo": "N172",
      "nombre": "Versense",
      "referencia": "Versace",
      "categoria": "femenino",
      "familia": "Cítrica / Floral",
      "perfil": "Cítrico, verde, fresco",
      "uso": "Primavera / verano",
      "nota": "Femenino fresco y elegante.",
      "imagen": "VersenseCat.jpeg",
      "imagenFicha": "Versense.jpeg"
    },
    {
      "codigo": "N173",
      "nombre": "Wanted Girl",
      "referencia": "Azzaro",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, moderno",
      "uso": "Día y noche",
      "nota": "Perfil femenino moderno y juvenil.",
      "imagen": "WantedGirlCat.jpeg",
      "imagenFicha": "WantedGirl.jpeg"
    },
    {
      "codigo": "N174",
      "nombre": "Fame",
      "referencia": "Paco Rabanne",
      "categoria": "femenino",
      "familia": "Floral / Amaderada",
      "perfil": "Dulce, frutal, moderno",
      "uso": "Noche",
      "nota": "Perfil femenino moderno, llamativo y dulce.",
      "imagen": "FameCat.jpeg",
      "imagenFicha": "Fame.jpeg"
    },
    {
      "codigo": "N178",
      "nombre": "Eros Femenino",
      "referencia": "Versace",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Dulce, floral, sensual",
      "uso": "Noche",
      "nota": "Femenino intenso y llamativo.",
      "imagen": "ErosFemeninoCat.jpeg",
      "imagenFicha": "ErosFemenino.jpeg"
    },
    {
      "codigo": "N180",
      "nombre": "Sì Passione",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, floral, dulce",
      "uso": "Día y noche",
      "nota": "Femenino moderno, romántico y fácil de recomendar.",
      "imagen": "SiPassioneCat.jpeg",
      "imagenFicha": "SiPassione.jpeg"
    },
    {
      "codigo": "N181",
      "nombre": "Alien Goddess",
      "referencia": "Mugler",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Dulce, cálido, luminoso",
      "uso": "Día y noche",
      "nota": "Perfil femenino moderno y radiante.",
      "imagen": "AlienGoddessCat.jpeg",
      "imagenFicha": "AlienGoddess.jpeg"
    },
    {
      "codigo": "N182",
      "nombre": "L'Interdit Rouge",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, especiado, intenso",
      "uso": "Noche / invierno",
      "nota": "Para quien quiere L'Interdit con mayor intensidad.",
      "imagen": "L'InterditRougeCat.jpeg",
      "imagenFicha": "L'InterditRouge.jpeg"
    },
    {
      "codigo": "N183",
      "nombre": "J'adore In Joy",
      "referencia": "Dior",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Fresco, floral, luminoso",
      "uso": "Primavera / verano",
      "nota": "J'adore más fresco y ligero.",
      "imagen": "J'adoreInJoyCat.jpeg",
      "imagenFicha": "J'adoreInJoy.jpeg"
    },
    {
      "codigo": "N184",
      "nombre": "Very Good Girl",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Rosa, frutal, dulce",
      "uso": "Noche",
      "nota": "Para quien busca un floral femenino moderno y sensual.",
      "imagen": "VeryGoodGirlCat.jpeg",
      "imagenFicha": "VeryGoodGirl.jpeg"
    },
    {
      "codigo": "N186",
      "nombre": "Irresistible Femenino",
      "referencia": "Givenchy",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Rosa, frutal, dulce",
      "uso": "Día y noche",
      "nota": "Perfil femenino moderno y romántico.",
      "imagen": "IrresistibleFemeninoCat.jpeg",
      "imagenFicha": "IrresistibleFemenino.jpeg"
    },
    {
      "codigo": "N189",
      "nombre": "212 Heroes Femenino",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Frutal, fresco, juvenil",
      "uso": "Día",
      "nota": "Perfil joven y casual.",
      "imagen": "212HeroesFemeninoCat.jpeg",
      "imagenFicha": "212HeroesFemenino.jpeg"
    },
    {
      "codigo": "N190",
      "nombre": "Scandal Le Parfum Femenino",
      "referencia": "Jean Paul Gaultier",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, miel, intenso",
      "uso": "Noche / invierno",
      "nota": "Para quien quiere dulzura e intensidad.",
      "imagen": "ScandalLeParfumFemeninoCat.jpeg",
      "imagenFicha": "ScandalLeParfumFemenino.jpeg"
    },
    {
      "codigo": "N191",
      "nombre": "My Way Le Parfum",
      "referencia": "Giorgio Armani",
      "categoria": "femenino",
      "familia": "Floral / Ambarada",
      "perfil": "Floral, cremoso, intenso",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien quiere un floral más profundo y sensual.",
      "imagen": "MyWayLeParfumCat.jpeg",
      "imagenFicha": "MyWayLeParfum.jpeg"
    },
    {
      "codigo": "N201",
      "nombre": "Black Opium Over Red",
      "referencia": "Yves Saint Laurent",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Café, cereza, dulce",
      "uso": "Noche / invierno",
      "nota": "Para quien busca Black Opium con un perfil frutal más intenso.",
      "imagen": "BlackOpiumOverRedCat.jpeg",
      "imagenFicha": "BlackOpiumOverRed.jpeg"
    },
    {
      "codigo": "N202",
      "nombre": "Good Girl Blush Elixir",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Gourmand",
      "perfil": "Dulce, floral, sensual",
      "uso": "Noche",
      "nota": "Para quien busca una versión más intensa y femenina.",
      "imagen": "GoodGirlBlushElixirCat.jpeg",
      "imagenFicha": "GoodGirlBlushElixir.jpeg"
    },
    {
      "codigo": "N203",
      "nombre": "Born in Roma",
      "referencia": "Valentino",
      "categoria": "femenino",
      "familia": "Amaderada / Aromática",
      "perfil": "Aromático, fresco, moderno",
      "uso": "Día y noche",
      "nota": "Moderno, versátil y fácil de usar.",
      "imagen": "BornInRomaCat.jpeg",
      "imagenFicha": "BornInRoma.jpeg"
    },
    {
      "codigo": "N204",
      "nombre": "La Belle Flower",
      "referencia": "Jean Paul Gaultier",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Dulce, floral, femenino",
      "uso": "Día y noche",
      "nota": "Perfil femenino moderno y dulce.",
      "imagen": "LaBelleFlowerCat.jpeg",
      "imagenFicha": "LaBelleFlower.jpeg"
    },
    {
      "codigo": "N210",
      "nombre": "La Vie Est Belle Elixir",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, intenso, femenino",
      "uso": "Noche / invierno",
      "nota": "Para amantes de los perfumes dulces y de alta presencia.",
      "imagen": "LaVieEstBelleElixirCat.jpeg",
      "imagenFicha": "LaVieEstBelleElixir.jpeg"
    },
    {
      "codigo": "N211",
      "nombre": "La Nuit Trésor Vanille",
      "referencia": "Lancôme",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Vainilla, dulce, intenso",
      "uso": "Noche / invierno",
      "nota": "Perfil femenino gourmand intenso y avainillado.",
      "imagen": "LaNuitTresorVanilleCat.jpeg",
      "imagenFicha": "LaNuitTresorVanille.jpeg"
    },
    {
      "codigo": "N212",
      "nombre": "Scandal Intense Femenino",
      "referencia": "Jean Paul Gaultier",
      "categoria": "femenino",
      "familia": "Gourmand / Floral",
      "perfil": "Dulce, intenso, sensual",
      "uso": "Noche / invierno",
      "nota": "Para quien quiere un aroma femenino potente y llamativo.",
      "imagen": "ScandalIntenseFemeninoCat.jpeg",
      "imagenFicha": "ScandalIntenseFemenino.jpeg"
    },
    {
      "codigo": "N213",
      "nombre": "La Bomba",
      "referencia": "Carolina Herrera",
      "categoria": "femenino",
      "familia": "Floral / Frutal",
      "perfil": "Floral, tropical, dulce",
      "uso": "Día y noche",
      "nota": "Floral tropical vibrante, con acordes frutales y un fondo dulce y cálido.",
      "imagen": "LaBombaCat.jpeg",
      "imagenFicha": "LaBomba.jpeg"
    },
  
    /* ==================== UNISEX ==================== */
    {
      "codigo": "N63",
      "nombre": "CK One",
      "referencia": "Calvin Klein",
      "categoria": "unisex",
      "familia": "Cítrica / Aromática",
      "perfil": "Fresco, limpio, unisex",
      "uso": "Día / verano",
      "nota": "Clásico unisex fresco y versátil.",
      "imagen": "CKOneCat.jpeg",
      "imagenFicha": "CKOne.jpeg"
    },
    {
      "codigo": "N117",
      "nombre": "Neroli Portofino",
      "referencia": "Tom Ford",
      "categoria": "unisex",
      "familia": "Cítrica / Aromática",
      "perfil": "Cítrico, limpio, mediterráneo",
      "uso": "Primavera / verano",
      "nota": "Unisex fresco y elegante, cítrico aromático.",
      "imagen": "NeroliPortofinoCat.jpeg",
      "imagenFicha": "NeroliPortofino.jpeg"
    },
    {
      "codigo": "N128",
      "nombre": "Oud Wood",
      "referencia": "Tom Ford",
      "categoria": "unisex",
      "familia": "Amaderada / Especiada",
      "perfil": "Oud, madera, especias",
      "uso": "Noche / otoño-invierno",
      "nota": "Perfil sofisticado y unisex para amantes de maderas.",
      "imagen": "OudWoodCat.jpeg",
      "imagenFicha": "OudWood.jpeg"
    },
    {
      "codigo": "N157",
      "nombre": "Tobacco Vanille",
      "referencia": "Tom Ford",
      "categoria": "unisex",
      "familia": "Gourmand / Ambarada",
      "perfil": "Tabaco, vainilla, cálido",
      "uso": "Noche / invierno",
      "nota": "Unisex intenso para amantes de vainilla y tabaco.",
      "imagen": "TobaccoVanilleCat.jpeg",
      "imagenFicha": "TobaccoVanille.jpeg"
    },
    {
      "codigo": "N159",
      "nombre": "Tom Ford Noir",
      "referencia": "Tom Ford",
      "categoria": "unisex",
      "familia": "Ambarada / Especiada",
      "perfil": "Especiado, dulce, elegante",
      "uso": "Noche",
      "nota": "Perfil sofisticado y nocturno.",
      "imagen": "TomFordNoirCat.jpeg",
      "imagenFicha": "TomFordNoir.jpeg"
    },
    {
      "codigo": "N179",
      "nombre": "Lost Cherry",
      "referencia": "Tom Ford",
      "categoria": "unisex",
      "familia": "Gourmand / Frutal",
      "perfil": "Cereza, almendra, dulce",
      "uso": "Noche",
      "nota": "Unisex llamativo, frutal y gourmand.",
      "imagen": "LostCherryCat.jpeg",
      "imagenFicha": "LostCherry.jpeg"
    },
    {
      "codigo": "N188",
      "nombre": "CK Be",
      "referencia": "Calvin Klein",
      "categoria": "unisex",
      "familia": "Cítrica / Almizclada",
      "perfil": "Limpio, fresco, suave",
      "uso": "Día / verano",
      "nota": "Unisex ligero y fácil para uso diario.",
      "imagen": "CKBeCat.jpeg",
      "imagenFicha": "CKBe.jpeg"
    },
    {
      "codigo": "N194",
      "nombre": "Erba Pura",
      "referencia": "Xerjoff",
      "categoria": "unisex",
      "familia": "Cítrica / Frutal / Almizclada",
      "perfil": "Frutal, fresca y potente",
      "uso": "Todo el año",
      "nota": "Unisex moderno, frutal y muy llamativo.",
      "imagen": "ErbaPuraCat.jpeg",
      "imagenFicha": "ErbaPura.jpeg"
    },
    {
      "codigo": "N195",
      "nombre": "Bade'e Al Oud Honor & Glory",
      "referencia": "Lattafa",
      "categoria": "unisex",
      "familia": "Ambarada / Gourmand",
      "perfil": "Dulce, cálido, especiado",
      "uso": "Noche / otoño-invierno",
      "nota": "Para quien busca un árabe intenso, dulce y llamativo.",
      "imagen": "Bade'eAlOudHonor&GloryCat.jpeg",
      "imagenFicha": "Bade'eAlOudHonor&Glory.jpeg"
    },
    {
      "codigo": "N196",
      "nombre": "Ishq Al Shuyukh Silver",
      "referencia": "Lattafa",
      "categoria": "unisex",
      "familia": "Amaderada / Frutal",
      "perfil": "Dulce, frutal, amaderado",
      "uso": "Noche",
      "nota": "Unisex de estilo árabe, moderno y llamativo.",
      "imagen": "IshqAlShuyukhSilverCat.jpeg",
      "imagenFicha": "IshqAlShuyukhSilver.jpeg"
    },
    {
      "codigo": "N199",
      "nombre": "Baccarat Rouge",
      "referencia": "Maison Francis Kurkdjian",
      "categoria": "unisex",
      "familia": "Ambarada / Amaderada",
      "perfil": "Dulce, aireado, sofisticado",
      "uso": "Todo el año",
      "nota": "Unisex muy reconocible, con perfil moderno y lujoso.",
      "imagen": "BaccaratRougeCat.jpeg",
      "imagenFicha": "BaccaratRouge.jpeg"
    },
    {
      "codigo": "N200",
      "nombre": "Noir de Noir",
      "referencia": "Tom Ford",
      "categoria": "unisex",
      "familia": "Ambarada / Floral",
      "perfil": "Rosa, oscuro, cálido",
      "uso": "Noche / otoño-invierno",
      "nota": "Unisex sofisticado y oscuro.",
      "imagen": "NoirDeNoirCat.jpeg",
      "imagenFicha": "NoirDeNoir.jpeg"
    },
    {
      "codigo": "N205",
      "nombre": "Khamrah Qahwa",
      "referencia": "Lattafa",
      "categoria": "unisex",
      "familia": "Gourmand / Oriental",
      "perfil": "Dulce, café, especiado",
      "uso": "Noche / otoño-invierno",
      "nota": "Versión con café del icónico Khamrah. Dulce, especiado y adictivo.",
      "imagen": "KhamrahQahwaCat.jpeg",
      "imagenFicha": "KhamrahQahwa.jpeg"
    },
    {
      "codigo": "N206",
      "nombre": "Amber Oud Gold",
      "referencia": "Al Haramain",
      "categoria": "unisex",
      "familia": "Ambarada / Frutal",
      "perfil": "Dulce, ambarado, frutal",
      "uso": "Noche / otoño-invierno",
      "nota": "Unisex árabe dulce y ambarado con un toque frutal.",
      "imagen": "AmberOudGoldCat.jpeg",
      "imagenFicha": "AmberOudGold.jpeg"
    },
    {
      "codigo": "N207",
      "nombre": "Erba Gold",
      "referencia": "Xerjoff",
      "categoria": "unisex",
      "familia": "Frutal / Floral / Almizclada",
      "perfil": "Frutal, dulce, luminoso",
      "uso": "Todo el año",
      "nota": "Unisex llamativo, ideal para quien disfruta perfumes frutales.",
      "imagen": "ErbaGoldCat.jpeg",
      "imagenFicha": "ErbaGold.jpeg"
    },
    {
      "codigo": "N208",
      "nombre": "Santal 33",
      "referencia": "Le Labo",
      "categoria": "unisex",
      "familia": "Amaderada / Especiada",
      "perfil": "Madera, especias, seco",
      "uso": "Todo el año",
      "nota": "Unisex de perfil artístico, seco y sofisticado.",
      "imagen": "Santal33Cat.jpeg",
      "imagenFicha": "Santal33.jpeg"
    }
  
  ];